"use client";

import { useEffect, useMemo, useState } from "react";
import { TIME_SLOTS } from "@/lib/time-slots";

type Court = { id: string; name: string; hourly_rate: number; is_active: boolean };
type Slot = { id: string; booking_date: string; start_minute: number; end_minute: number; hourly_rate: number; status: string; courts?: { name?: string } | null };
type Booking = { id: string; booking_code: string; customer_name: string; customer_mobile: string; customer_email: string; total_hours: number; total_amount: number; payment_status: string; booking_status: string; proof_url?: string | null; created_at: string; booking_slots?: Slot[] };
type ScheduleRow = { bookingId: string; bookingCode: string; customerName: string; customerMobile: string; customerEmail: string; paymentStatus: string; bookingStatus: string; proofUrl?: string | null; slot: Slot };

const formatTime = (minute: number) => { const h24 = Math.floor(minute / 60) % 24; const suffix = h24 >= 12 ? "PM" : "AM"; const h = h24 % 12 === 0 ? 12 : h24 % 12; return `${h}:00 ${suffix}`; };
const localISODate = (date = new Date()) => { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, "0"); const day = String(date.getDate()).padStart(2, "0"); return `${year}-${month}-${day}`; };
const addDays = (iso: string, days: number) => { const d = new Date(`${iso}T12:00:00`); d.setDate(d.getDate() + days); return localISODate(d); };
const shortDate = (iso: string) => { const [y, m, d] = iso.split("-").map(Number); return new Date(y, m - 1, d).toLocaleDateString(undefined, { month: "short", day: "numeric" }); };
const php = (value: number) => `₱${Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;

export default function AdminPage() {
  const today = localISODate();
  const [code, setCode] = useState("");
  const [courts, setCourts] = useState<Court[]>([]);
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [fromDate, setFromDate] = useState(today);
  const [toDate, setToDate] = useState(addDays(today, 6));
  const [draftFrom, setDraftFrom] = useState(today);
  const [draftTo, setDraftTo] = useState(addDays(today, 6));
  const [msg, setMsg] = useState("");
  const [loading, setLoading] = useState(false);
  const [showOpenSlotsReport, setShowOpenSlotsReport] = useState(false);

  const loadCourts = () => fetch("/api/admin/courts").then(r => r.json()).then(d => setCourts(d.courts || []));
  useEffect(() => { loadCourts(); }, []);

  async function loadBookings() { setLoading(true); setMsg(""); try { const r = await fetch(`/api/admin/bookings?adminCode=${encodeURIComponent(code)}`); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Unable to load bookings"); setBookings(d.bookings || []); } catch (e: any) { setMsg(e.message || "Unable to load bookings"); } finally { setLoading(false); } }
  async function saveCourt(c: Court) { setMsg(""); const r = await fetch("/api/admin/courts", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ adminCode: code, courtId: c.id, hourlyRate: c.hourly_rate, isActive: c.is_active }) }); const d = await r.json(); setMsg(r.ok ? `${c.name} updated.` : (d.error || "Update failed")); }
  function resetSevenDays() { const start = localISODate(); const end = addDays(start, 6); setDraftFrom(start); setDraftTo(end); setFromDate(start); setToDate(end); }
  function applyDateFilter() { if (!draftFrom || !draftTo) return setMsg("Select both From and To dates."); if (draftFrom > draftTo) return setMsg("From date cannot be after To date."); setMsg(""); setFromDate(draftFrom); setToDate(draftTo); }

  const scheduleRows = useMemo<ScheduleRow[]>(() => { const rows: ScheduleRow[] = []; for (const booking of bookings) for (const slot of booking.booking_slots || []) { if (slot.booking_date < fromDate || slot.booking_date > toDate) continue; rows.push({ bookingId: booking.id, bookingCode: booking.booking_code, customerName: booking.customer_name, customerMobile: booking.customer_mobile, customerEmail: booking.customer_email, paymentStatus: booking.payment_status, bookingStatus: booking.booking_status, proofUrl: booking.proof_url, slot }); } return rows.sort((a,b) => a.slot.booking_date.localeCompare(b.slot.booking_date) || (a.slot.courts?.name || "").localeCompare(b.slot.courts?.name || "") || a.slot.start_minute-b.slot.start_minute); }, [bookings, fromDate, toDate]);

  const periodReport = useMemo(() => { const activeRows = scheduleRows.filter(r => r.bookingStatus !== "cancelled"); const paidRows = activeRows.filter(r => r.paymentStatus === "paid"); const bookedRows = activeRows.filter(r => r.bookingStatus === "confirmed" && r.paymentStatus === "paid"); const uniqueBookings = new Set(activeRows.map(r => r.bookingId)).size; const paidBookings = new Set(paidRows.map(r => r.bookingId)).size; const sales = paidRows.reduce((sum,r) => sum + Number(r.slot.hourly_rate || 0),0); const bookedHours = bookedRows.length; const days = Math.max(1, Math.round((new Date(`${toDate}T12:00:00`).getTime()-new Date(`${fromDate}T12:00:00`).getTime())/86400000)+1); const activeCourts = courts.filter(c=>c.is_active).length; const totalSlots=activeCourts*24*days; const openSlots=Math.max(0,totalSlots-activeRows.length); const utilization=totalSlots?(activeRows.length/totalSlots)*100:0; return {sales,bookedHours,uniqueBookings,paidBookings,totalSlots,openSlots,utilization,days}; }, [scheduleRows,courts,fromDate,toDate]);

  const dateSeries = useMemo(() => { const result:{date:string;label:string;sales:number;hours:number;booked:number;open:number}[]=[]; const activeCourtCount=courts.filter(c=>c.is_active).length; let cursor=fromDate; let guard=0; while(cursor<=toDate&&guard<62){ const dayRows=scheduleRows.filter(r=>r.slot.booking_date===cursor&&r.bookingStatus!=="cancelled"); const paid=dayRows.filter(r=>r.paymentStatus==="paid"); result.push({date:cursor,label:shortDate(cursor),sales:paid.reduce((sum,r)=>sum+Number(r.slot.hourly_rate||0),0),hours:paid.filter(r=>r.bookingStatus==="confirmed").length,booked:dayRows.length,open:Math.max(0,activeCourtCount*24-dayRows.length)}); cursor=addDays(cursor,1); guard++; } return result; },[scheduleRows,courts,fromDate,toDate]);
  const selectedMonthStart=`${fromDate.slice(0,7)}-01`;
  const selectedMonthDate=new Date(`${selectedMonthStart}T12:00:00`);
  const selectedMonthDays=new Date(selectedMonthDate.getFullYear(),selectedMonthDate.getMonth()+1,0).getDate();
  const previousMonthDate=new Date(selectedMonthDate.getFullYear(),selectedMonthDate.getMonth()-1,1);
  const previousMonthStart=localISODate(previousMonthDate);
  const previousMonthDays=new Date(previousMonthDate.getFullYear(),previousMonthDate.getMonth()+1,0).getDate();
  const selectedMonthLabel=selectedMonthDate.toLocaleDateString(undefined,{month:"long",year:"numeric"});
  const previousMonthLabel=previousMonthDate.toLocaleDateString(undefined,{month:"long",year:"numeric"});
  const monthlySales=(start:string,days:number)=>Array.from({length:days},(_,index)=>{const date=addDays(start,index);let sales=0;for(const booking of bookings){if(booking.booking_status==="cancelled"||booking.payment_status!=="paid")continue;for(const slot of booking.booking_slots||[]){if(slot.booking_date===date)sales+=Number(slot.hourly_rate||0);}}return {date,label:shortDate(date),sales};});
  const selectedMonthSeries=useMemo(()=>monthlySales(selectedMonthStart,selectedMonthDays),[bookings,selectedMonthStart,selectedMonthDays]);
  const previousMonthSeries=useMemo(()=>monthlySales(previousMonthStart,previousMonthDays),[bookings,previousMonthStart,previousMonthDays]);
  const selectedMonthSales=selectedMonthSeries.reduce((sum,day)=>sum+day.sales,0);
  const previousMonthSales=previousMonthSeries.reduce((sum,day)=>sum+day.sales,0);
  const monthlySalesChange=previousMonthSales?((selectedMonthSales-previousMonthSales)/previousMonthSales)*100:null;
  const monthlyBestDay=Math.max(0,...selectedMonthSeries.map(day=>day.sales));
  const monthlyDailyAverage=selectedMonthDays?selectedMonthSales/selectedMonthDays:0;
  const rawMonthlyMax=Math.max(1,...selectedMonthSeries.map(day=>day.sales),...previousMonthSeries.map(day=>day.sales));
  const monthlyYAxisMax=Math.max(1000,Math.ceil(rawMonthlyMax/1000)*1000);
  const linePoint=(sales:number,index:number,count:number)=>({x:78+(index/Math.max(1,count-1))*900,y:270-(sales/monthlyYAxisMax)*225});
  const selectedLinePoints=selectedMonthSeries.map((day,index)=>{const p=linePoint(day.sales,index,selectedMonthSeries.length);return `${p.x},${p.y}`;}).join(" ");
  const previousLinePoints=previousMonthSeries.map((day,index)=>{const p=linePoint(day.sales,index,previousMonthSeries.length);return `${p.x},${p.y}`;}).join(" ");
  const selectedAreaPoints=`78,270 ${selectedLinePoints} 978,270`;
  const monthlyAxisTicks=Array.from(new Set([0,4,9,14,19,24,selectedMonthSeries.length-1])).filter(index=>index>=0&&index<selectedMonthSeries.length);
  const monthlyYTicks=Array.from({length:5},(_,index)=>({y:45+(index*225)/4,value:monthlyYAxisMax*(4-index)/4}));
  const availabilityByCourt=useMemo(()=>{ const activeCourts=courts.filter(c=>c.is_active); return dateSeries.map(day=>({date:day.date,courts:activeCourts.map(court=>{const rows=scheduleRows.filter(r=>r.slot.booking_date===day.date&&r.bookingStatus!=="cancelled"&&(r.slot.courts?.name||"")===court.name);const bookedStarts=new Set(rows.map(r=>r.slot.start_minute));const openSlots=TIME_SLOTS.filter(slot=>!bookedStarts.has(slot.startMinute));return {name:court.name,booked:rows.length,open:openSlots.length,openSlots,occupancy:(rows.length/TIME_SLOTS.length)*100};})})); },[dateSeries,courts,scheduleRows]);

  function exportCSV(){ const rows=[["Booking Date","Court","Time","Booking Reference","Customer","Mobile","Email","Booking Status","Payment Status","Rate"],...scheduleRows.map(r=>[r.slot.booking_date,r.slot.courts?.name||"Court",`${formatTime(r.slot.start_minute)} - ${formatTime(r.slot.end_minute)}`,r.bookingCode,r.customerName,r.customerMobile,r.customerEmail,r.bookingStatus,r.paymentStatus,Number(r.slot.hourly_rate||0).toFixed(2)])]; const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"); const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=`booking-report-${fromDate}-to-${toDate}.csv`; a.click(); URL.revokeObjectURL(url); }
  function exportOpenSlotsCSV(){ const rows=[["Date","Court","Open Time Slot"],...availabilityByCourt.flatMap(day=>day.courts.flatMap(court=>court.openSlots.map(slot=>[day.date,court.name,slot.label])))]; const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"); const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=`open-slots-${fromDate}-to-${toDate}.csv`; a.click(); URL.revokeObjectURL(url); }

  return <main className="container">
    <section className="hero"><div className="logoBox">BUELO</div><div><span className="pill">ADMIN DASHBOARD</span><h1>Booking & Sales Dashboard</h1><p>Monitor the next 7 days by default, or filter a specific date range for schedules, sales and remaining court availability.</p></div></section>
    <section className="card"><div className="grid grid-2"><div><label>Admin password</label><input type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter ADMIN_PASSWORD" /></div><div style={{display:"flex",alignItems:"end"}}><button className="btn btn-primary" onClick={loadBookings} disabled={loading||!code}>{loading?"Loading...":"Open Dashboard"}</button></div></div></section>
    {bookings.length>0&&<>
      <section className="card" style={{marginTop:16}}><div className="row space"><div><span className="pill">DASHBOARD FILTER</span><h2 style={{marginBottom:6}}>Schedule Period</h2><div className="muted">Default view is today plus the next 6 days (7 days total).</div></div><button className="btn btn-secondary" onClick={exportCSV}>Export CSV</button></div><div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",marginTop:16}}><div><label>From date</label><input type="date" value={draftFrom} onChange={e=>setDraftFrom(e.target.value)}/></div><div><label>To date</label><input type="date" value={draftTo} onChange={e=>setDraftTo(e.target.value)}/></div><div style={{display:"flex",alignItems:"end",gap:10,flexWrap:"wrap"}}><button className="btn btn-primary" onClick={applyDateFilter}>Apply Filter</button><button className="btn btn-secondary" onClick={resetSevenDays}>Reset 7 Days</button><button className="btn btn-secondary" onClick={loadBookings}>Refresh</button></div></div><p className="muted" style={{marginBottom:0}}>Showing <strong>{fromDate}</strong> to <strong>{toDate}</strong> · {periodReport.days} day(s)</p></section>
      <div className="grid metric-grid"><section className="card"><div className="muted">Sales</div><div className="price">{php(periodReport.sales)}</div><div className="muted">Selected period</div></section><section className="card"><div className="muted">Reservations</div><div className="price">{periodReport.uniqueBookings}</div><div className="muted">Active bookings</div></section><section className="card"><div className="muted">Booked Hours</div><div className="price">{periodReport.bookedHours}</div><div className="muted">Confirmed + paid</div></section><button type="button" className="card open-slots-kpi" onClick={()=>setShowOpenSlotsReport(true)}><div className="muted">Open Slots</div><div className="price">{periodReport.openSlots}</div><div className="muted">Click to view printable report</div></button><section className="card"><div className="muted">Occupancy</div><div className="price">{periodReport.utilization.toFixed(1)}%</div><div className="muted">Across active courts</div></section><section className="card"><div className="muted">Paid Bookings</div><div className="price">{periodReport.paidBookings}</div><div className="muted">Selected period</div></section></div>
      <section className="card sales-comparison-card monthly-sales-card">
        <div className="sales-comparison-header">
          <div><span className="pill">SALES GROWTH</span><h2>Monthly Sales Comparison</h2><div className="sales-chart-legend"><span><i className="legend-line selected-line-key"/>{selectedMonthLabel}</span><span><i className="legend-line previous-line-key"/>{previousMonthLabel}</span></div><div className="monthly-insights"><span>★ Best day <strong>{php(monthlyBestDay)}</strong></span><span>⌁ Daily average <strong>{php(monthlyDailyAverage)}</strong></span><span>▣ {selectedMonthDays} days</span></div></div>
          <div className="sales-comparison-totals"><div><strong className="selected-total">{php(selectedMonthSales)}</strong><span>Selected month</span></div><div><strong className="previous-total">{php(previousMonthSales)}</strong><span>Previous month</span></div><div className={`sales-change ${monthlySalesChange!==null&&monthlySalesChange<0?"negative":"positive"}`}><strong>{monthlySalesChange===null?"New":`${monthlySalesChange>=0?"↑":"↓"} ${Math.abs(monthlySalesChange).toFixed(1)}%`}</strong><span>Compared with previous month</span></div></div>
        </div>
        <div className="monthly-chart-wrap">
          <svg className="monthly-line-chart" viewBox="0 0 1000 310" role="img" aria-label={`Sales comparison for ${selectedMonthLabel} and ${previousMonthLabel}`}>
            <defs><linearGradient id="selectedSalesArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#20d9e5" stopOpacity=".38"/><stop offset="100%" stopColor="#20d9e5" stopOpacity=".02"/></linearGradient></defs>
            {monthlyYTicks.map(tick=><g key={tick.y}><line x1="78" y1={tick.y} x2="978" y2={tick.y} className="monthly-grid-line"/><text x="68" y={tick.y+4} textAnchor="end" className="monthly-y-label">{php(tick.value)}</text></g>)}
            <polygon points={selectedAreaPoints} fill="url(#selectedSalesArea)"/>
            <polyline points={previousLinePoints} className="monthly-line previous-month-line"/>
            <polyline points={selectedLinePoints} className="monthly-line selected-month-line"/>
            {previousMonthSeries.map((day,index)=>{const p=linePoint(day.sales,index,previousMonthSeries.length);return <circle key={day.date} cx={p.x} cy={p.y} r="3" className="monthly-point previous-point"><title>{day.date}: {php(day.sales)}</title></circle>})}
            {selectedMonthSeries.map((day,index)=>{const p=linePoint(day.sales,index,selectedMonthSeries.length);return <circle key={day.date} cx={p.x} cy={p.y} r="3.5" className="monthly-point selected-point"><title>{day.date}: {php(day.sales)}</title></circle>})}
            {monthlyAxisTicks.map(index=>{const day=selectedMonthSeries[index];const p=linePoint(day.sales,index,selectedMonthSeries.length);return <text key={`value-${day.date}`} x={p.x} y={Math.max(18,p.y-11)} textAnchor="middle" className="monthly-value-label">{php(day.sales)}</text>})}
          </svg>
          <div className="monthly-axis-labels">{monthlyAxisTicks.map(index=><span key={selectedMonthSeries[index].date} style={{left:`${(index/Math.max(1,selectedMonthSeries.length-1))*100}%`}}>{selectedMonthSeries[index].label}</span>)}</div>
        </div>
      </section>
      <section className="card" style={{marginTop:16}}><div className="row space"><div><span className="pill">BOOKING SCHEDULE</span><h2>{fromDate===toDate?`Schedule for ${fromDate}`:`${shortDate(fromDate)} – ${shortDate(toDate)}`}</h2></div><span className="pill">{scheduleRows.length} SLOT(S)</span></div>{scheduleRows.length===0?<p className="muted">No booking schedule found for this period.</p>:<div className="schedule-table-wrap"><table className="schedule-table"><thead><tr><th style={{padding:10}}>Date</th><th style={{padding:10}}>Time</th><th style={{padding:10}}>Court</th><th style={{padding:10}}>Customer</th><th style={{padding:10}}>Booking Ref</th><th style={{padding:10}}>Booking</th><th style={{padding:10}}>Payment</th><th style={{padding:10}}>Rate</th><th style={{padding:10}}>Proof</th></tr></thead><tbody>{scheduleRows.map(row=><tr key={`${row.bookingId}-${row.slot.id}`}><td style={{padding:10}}>{row.slot.booking_date}</td><td style={{padding:10,whiteSpace:"nowrap"}}>{formatTime(row.slot.start_minute)} - {formatTime(row.slot.end_minute)}</td><td style={{padding:10}}>{row.slot.courts?.name||"Court"}</td><td style={{padding:10}}><strong>{row.customerName}</strong><div className="muted" style={{fontSize:12}}>{row.customerMobile}</div></td><td style={{padding:10}}>{row.bookingCode}</td><td style={{padding:10}}><span className="pill">{row.bookingStatus}</span></td><td style={{padding:10}}><span className="pill">{row.paymentStatus.replaceAll("_"," ")}</span></td><td style={{padding:10}}>{php(row.slot.hourly_rate)}</td><td style={{padding:10}}>{row.proofUrl?<a className="btn btn-secondary" href={row.proofUrl} target="_blank" rel="noreferrer">View</a>:<span className="muted">None</span>}</td></tr>)}</tbody></table></div>}</section>
    </>}
    <section style={{marginTop:24}}><div className="row space"><div><span className="pill">COURT SETTINGS</span><h2>Rates & Availability</h2></div></div><div className="grid grid-2">{courts.map(c=><section className="card" key={c.id}><h2>{c.name}</h2><label>Hourly rate (PHP)</label><input type="number" value={c.hourly_rate} onChange={e=>setCourts(p=>p.map(x=>x.id===c.id?{...x,hourly_rate:Number(e.target.value)}:x))}/><div className="row" style={{marginTop:14}}><label style={{margin:0}}><input style={{width:"auto"}} type="checkbox" checked={c.is_active} onChange={e=>setCourts(p=>p.map(x=>x.id===c.id?{...x,is_active:e.target.checked}:x))}/> Active</label><button className="btn btn-primary" onClick={()=>saveCourt(c)}>Save</button></div></section>)}</div></section>
    {msg&&<p className={msg.toLowerCase().includes("updated")?"success":"error"}>{msg}</p>}
    {showOpenSlotsReport&&<div className="open-slots-overlay" role="dialog" aria-modal="true" aria-labelledby="open-slots-report-title" onClick={()=>setShowOpenSlotsReport(false)}><section className="open-slots-modal" onClick={e=>e.stopPropagation()}>
      <div className="row space open-slots-report-actions"><div><span className="pill">AVAILABILITY REPORT</span><h2 id="open-slots-report-title">Remaining Open Slots</h2><div className="muted">{fromDate} to {toDate}</div></div><div className="row"><button className="btn btn-secondary" onClick={exportOpenSlotsCSV}>Export CSV</button><button className="btn btn-primary" onClick={()=>window.print()}>Print Report</button><button className="btn btn-secondary" onClick={()=>setShowOpenSlotsReport(false)}>Close</button></div></div>
      <div className="availability-report open-slots-print-report">{availabilityByCourt.map(day=><div key={day.date} className="availability-day"><strong className="availability-date">{shortDate(day.date)} <span className="muted">({day.date})</span></strong>{day.courts.map(c=><div key={`${day.date}-${c.name}`} className="availability-court open-slots-report-court"><div className="open-slots-report-summary"><strong>{c.name}</strong><span><strong>{c.open}</strong> open · {c.booked} booked · {c.occupancy.toFixed(0)}% occupied</span></div><div className="availability-slots">{c.openSlots.length?c.openSlots.map(slot=><span className="availability-slot" key={`${day.date}-${c.name}-${slot.startMinute}`}>{slot.label}</span>):<span className="muted">No open slots.</span>}</div></div>)}</div>)}</div>
    </section></div>}
  </main>;
}
