"use client";

import { useMemo, useState } from "react";
import { TIME_SLOTS } from "@/lib/time-slots";

type Court={id:string;name:string;hourly_rate:number;is_active:boolean};
type Slot={id:string;booking_date:string;start_minute:number;end_minute:number;hourly_rate:number;status:string;court_id:string;courts?:{id?:string;name?:string}|null};
type Booking={id:string;booking_code:string;customer_name:string;customer_mobile:string;customer_email:string;total_hours:number;total_amount:number;payment_status:string;booking_status:string;proof_url?:string|null;admin_notes?:string;created_at:string;booking_slots?:Slot[]};
type Refund={id:string;booking_id:string;amount:number;reason:string;notes:string;status:string;requested_at:string};
type Event={id:string;booking_id:string;event_type:string;details:any;created_at:string};

const money=(n:number)=>`₱${Number(n||0).toLocaleString()}`;
const fmt=(m:number)=>TIME_SLOTS.find(x=>x.startMinute===m)?.label.split(" - ")[0]||`${m}`;

export default function ManageReservations(){
 const[code,setCode]=useState(""); const[data,setData]=useState<{bookings:Booking[];refunds:Refund[];events:Event[];courts:Court[]}>({bookings:[],refunds:[],events:[],courts:[]});
 const[query,setQuery]=useState(""); const[status,setStatus]=useState("all"); const[msg,setMsg]=useState(""); const[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);setMsg("");try{const r=await fetch(`/api/admin/operations?adminCode=${encodeURIComponent(code)}`);const d=await r.json();if(!r.ok)throw new Error(d.setupRequired?"Run supabase/phase2_operations.sql in Supabase SQL Editor first.":d.error||"Unable to load");setData(d);}catch(e:any){setMsg(e.message)}finally{setLoading(false)}};
 const act=async(action:string,bookingId:string,extra:any={})=>{setMsg("");const r=await fetch("/api/admin/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({adminCode:code,action,bookingId,...extra})});const d=await r.json();if(!r.ok){setMsg(d.error||"Action failed");return false;}setMsg("Action completed.");await load();return true;};
 const visible=useMemo(()=>data.bookings.filter(b=>{const q=query.toLowerCase().trim();const matches=!q||[b.booking_code,b.customer_name,b.customer_mobile,b.customer_email].join(" ").toLowerCase().includes(q);const matchesStatus=status==="all"||b.booking_status===status||b.payment_status===status;return matches&&matchesStatus;}),[data.bookings,query,status]);
 const pending=data.bookings.filter(b=>b.payment_status==="pending_verification").length; const verified=data.bookings.filter(b=>b.payment_status==="verified").length; const confirmed=data.bookings.filter(b=>b.booking_status==="confirmed").length; const refundOpen=data.refunds.filter(r=>["requested","approved"].includes(r.status)).length; const paidRevenue=data.bookings.filter(b=>b.payment_status==="paid"&&b.booking_status!=="cancelled").reduce((s,b)=>s+Number(b.total_amount||0),0); const refunded=data.refunds.filter(r=>r.status==="completed").reduce((s,r)=>s+Number(r.amount||0),0);
 return <main className="container">
  <section className="hero"><div className="logoBox">BUELO</div><div><span className="pill">OPERATIONS</span><h1>Reservations Control Center</h1><p>Verify payments, confirm bookings, reschedule court slots, process refunds, and review the audit trail.</p></div></section>
  <section className="card"><div className="grid grid-2"><div><label>Admin password</label><input type="password" value={code} onChange={e=>setCode(e.target.value)} /></div><div style={{display:"flex",alignItems:"end"}}><button className="btn btn-primary" disabled={!code||loading} onClick={load}>{loading?"Loading...":"Open Operations"}</button></div></div>{msg&&<p className={msg.includes("completed")?"success":"error"}>{msg}</p>}</section>
  {data.bookings.length>0&&<>
   <div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",marginTop:16}}>
    <section className="card"><div className="muted">Pending Verification</div><div className="price">{pending}</div></section><section className="card"><div className="muted">Payment Verified</div><div className="price">{verified}</div></section><section className="card"><div className="muted">Confirmed</div><div className="price">{confirmed}</div></section><section className="card"><div className="muted">Open Refunds</div><div className="price">{refundOpen}</div></section><section className="card"><div className="muted">Paid Revenue</div><div className="price">{money(paidRevenue)}</div></section><section className="card"><div className="muted">Refunded</div><div className="price">{money(refunded)}</div></section>
   </div>
   <section className="card" style={{marginTop:16}}><div className="grid grid-2"><div><label>Search booking, customer, phone or email</label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search..."/></div><div><label>Status filter</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All</option><option value="pending">Pending booking</option><option value="pending_verification">Payment to verify</option><option value="verified">Payment verified</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option><option value="refunded">Refunded</option></select></div></div></section>
   <section className="card" style={{marginTop:16}}><div className="row space"><div><span className="pill">REVIEW QUEUE</span><h2>Reservations</h2></div><span className="pill">{visible.length} RESULT(S)</span></div><div className="grid">
    {visible.map(b=>{const refund=data.refunds.find(r=>r.booking_id===b.id);const events=data.events.filter(e=>e.booking_id===b.id).slice(0,8);return <article key={b.id} style={{border:"1px solid #244d87",borderRadius:16,padding:16,background:"#081a34"}}>
      <div className="row space"><div><strong>{b.customer_name}</strong><div className="muted">{b.booking_code} · {b.customer_mobile}{b.customer_email?` · ${b.customer_email}`:""}</div></div><div style={{textAlign:"right"}}><strong>{money(b.total_amount)}</strong><div className="muted">{b.total_hours} hour(s)</div></div></div>
      <div className="row" style={{marginTop:10}}><span className="pill">Booking: {b.booking_status}</span><span className="pill">Payment: {b.payment_status}</span>{refund&&<span className="pill">Refund: {refund.status}</span>}</div>
      <div className="grid grid-2" style={{marginTop:14}}><div><h3>Payment Review</h3>{b.proof_url?<a className="btn btn-secondary" href={b.proof_url} target="_blank" rel="noreferrer">View Payment Proof</a>:<div className="muted">No proof uploaded.</div>}<div className="row" style={{marginTop:10}}><button className="btn btn-primary" onClick={()=>act("verify_payment",b.id)}>Verify Payment</button><button className="btn btn-danger" onClick={()=>{const reason=prompt("Reason for rejecting payment?")||"Payment proof rejected";act("reject_payment",b.id,{reason})}}>Reject</button></div></div>
      <div><h3>Booking Approval</h3><div className="row"><button className="btn btn-primary" disabled={!['verified','paid'].includes(b.payment_status)||b.booking_status==='confirmed'} onClick={()=>act("confirm_booking",b.id)}>Confirm Booking</button><button className="btn btn-danger" onClick={()=>{const reason=prompt("Cancellation reason?")||"Cancelled by admin";act("cancel_booking",b.id,{reason})}}>Cancel Booking</button></div></div></div>
      <div style={{marginTop:16}}><h3>Schedule & Reschedule</h3><div className="grid">{(b.booking_slots||[]).map(s=><div key={s.id} className="card" style={{padding:12}}><div className="row space"><div><strong>{s.booking_date}</strong> · {s.courts?.name||"Court"} · {fmt(s.start_minute)} <span className="muted">({s.status})</span></div><button className="btn btn-secondary" onClick={async()=>{const date=prompt("New date (YYYY-MM-DD)",s.booking_date);if(!date)return;const courtName=prompt("New court: UNO Court or DOS Court",s.courts?.name||"");if(!courtName)return;const court=data.courts.find(c=>c.name.toLowerCase()===courtName.toLowerCase());if(!court){setMsg("Court not found.");return;}const time=prompt("New start hour in 24h format (example 19 for 7 PM)",String(Math.floor(s.start_minute/60)));if(time===null)return;const hour=Number(time);if(!Number.isInteger(hour)||hour<0||hour>23){setMsg("Invalid hour.");return;}await act("reschedule_slot",b.id,{slotId:s.id,bookingDate:date,courtId:court.id,startMinute:hour*60});}}>Reschedule</button></div></div>)}</div></div>
      <div className="grid grid-2" style={{marginTop:16}}><div><h3>Refund</h3>{!refund&&<button className="btn btn-secondary" onClick={()=>{const reason=prompt("Refund reason?")||"Customer refund request";act("request_refund",b.id,{amount:b.total_amount,reason})}}>Request Refund</button>}{refund?.status==='requested'&&<div className="row"><button className="btn btn-primary" onClick={()=>act("approve_refund",b.id)}>Approve Refund</button><button className="btn btn-danger" onClick={()=>act("reject_refund",b.id,{reason:prompt("Reason?")||"Refund rejected"})}>Reject</button></div>}{refund?.status==='approved'&&<button className="btn btn-primary" onClick={()=>act("complete_refund",b.id)}>Mark Refund Completed</button>}{refund&&<div className="muted" style={{marginTop:8}}>{money(refund.amount)} · {refund.reason}</div>}</div>
      <div><h3>Admin Notes</h3><textarea defaultValue={b.admin_notes||""} id={`note-${b.id}`} style={{width:"100%",minHeight:80,background:"#081a34",color:"white",border:"1px solid #315f9f",borderRadius:12,padding:10}}/><button className="btn btn-secondary" style={{marginTop:8}} onClick={()=>{const el=document.getElementById(`note-${b.id}`) as HTMLTextAreaElement|null;act("save_note",b.id,{note:el?.value||""})}}>Save Note</button></div></div>
      <div style={{marginTop:16}}><h3>Audit Trail</h3>{events.length===0?<div className="muted">No events yet.</div>:events.map(e=><div key={e.id} className="muted" style={{marginBottom:5}}>{new Date(e.created_at).toLocaleString()} · <strong>{e.event_type.replaceAll('_',' ')}</strong></div>)}</div>
    </article>})}
   </div></section>
  </>}
 </main>;
}
