"use client";

import { useMemo, useState } from "react";
import { TIME_SLOTS } from "@/lib/time-slots";

type Court={id:string;name:string;hourly_rate:number;is_active:boolean};
type Slot={id:string;booking_date:string;start_minute:number;end_minute:number;hourly_rate:number;status:string;court_id:string;courts?:{id?:string;name?:string}|null};
type Booking={id:string;booking_code:string;customer_name:string;customer_mobile:string;customer_email:string;total_hours:number;total_amount:number;payment_status:string;booking_status:string;proof_url?:string|null;admin_notes?:string;created_at:string;booking_slots?:Slot[]};
type Refund={id:string;booking_id:string;amount:number;reason:string;notes:string;status:string;requested_at:string};
type Event={id:string;booking_id:string;event_type:string;details:any;created_at:string};

const money=(n:number)=>`₱${Number(n||0).toLocaleString()}`;
const dateInputValue=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const todayDate=()=>dateInputValue(new Date());
const nextSevenDaysEnd=()=>{const date=new Date();date.setDate(date.getDate()+6);return dateInputValue(date)};
const fmt=(m:number)=>TIME_SLOTS.find(x=>x.startMinute===m)?.label.split(" - ")[0]||`${m}`;
const statusTone=(value:string)=>{
  if(["confirmed","paid","verified","completed"].includes(value)) return {bg:"#123d2b",border:"#2d8b61",color:"#bfffe0"};
  if(["pending","pending_verification","requested","approved"].includes(value)) return {bg:"#4a3a12",border:"#9f7a23",color:"#ffe6a1"};
  if(["cancelled","rejected","refunded"].includes(value)) return {bg:"#4b2028",border:"#9a4050",color:"#ffd0d8"};
  return {bg:"#12305b",border:"#356eb3",color:"#dcecff"};
};
const StatusBadge=({label,value}:{label:string;value:string})=>{const t=statusTone(value);return <span style={{display:"inline-flex",alignItems:"center",gap:6,padding:"6px 10px",borderRadius:999,background:t.bg,border:`1px solid ${t.border}`,color:t.color,fontSize:12,fontWeight:700}}><span style={{width:7,height:7,borderRadius:99,background:t.color}}/>{label}: {value.replaceAll("_"," ")}</span>};

export default function ManageReservations(){
 const[code,setCode]=useState(""); const[data,setData]=useState<{bookings:Booking[];refunds:Refund[];events:Event[];courts:Court[]}>({bookings:[],refunds:[],events:[],courts:[]});
 const[query,setQuery]=useState(""); const[status,setStatus]=useState("all"); const[fromDate,setFromDate]=useState(todayDate); const[toDate,setToDate]=useState(nextSevenDaysEnd); const[appliedQuery,setAppliedQuery]=useState(""); const[appliedStatus,setAppliedStatus]=useState("all"); const[appliedFromDate,setAppliedFromDate]=useState(todayDate); const[appliedToDate,setAppliedToDate]=useState(nextSevenDaysEnd); const[msg,setMsg]=useState(""); const[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);setMsg("");try{const r=await fetch(`/api/admin/operations?adminCode=${encodeURIComponent(code)}`);const d=await r.json();if(!r.ok)throw new Error(d.setupRequired?"Run supabase/phase2_operations.sql in Supabase SQL Editor first.":d.error||"Unable to load");setData(d);}catch(e:any){setMsg(e.message)}finally{setLoading(false)}};
 const act=async(action:string,bookingId:string,extra:any={})=>{setMsg("");const r=await fetch("/api/admin/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({adminCode:code,action,bookingId,...extra})});const d=await r.json();if(!r.ok){setMsg(d.error||"Action failed");return false;}setMsg("Action completed.");await load();return true;};
 const runSearch=()=>{if(fromDate&&toDate&&fromDate>toDate){setMsg("From date cannot be after To date.");return}setMsg("");setAppliedQuery(query.trim());setAppliedStatus(status);setAppliedFromDate(fromDate);setAppliedToDate(toDate);};
 const applyNextSevenDays=()=>{const start=todayDate();const end=nextSevenDaysEnd();setFromDate(start);setToDate(end);setAppliedFromDate(start);setAppliedToDate(end);setMsg("");};
 const clearSearch=()=>{setQuery("");setStatus("all");setFromDate("");setToDate("");setAppliedQuery("");setAppliedStatus("all");setAppliedFromDate("");setAppliedToDate("");setMsg("");};
 const visible=useMemo(()=>data.bookings.filter(b=>{const q=appliedQuery.toLowerCase().trim();const matches=!q||[b.booking_code,b.customer_name,b.customer_mobile,b.customer_email].join(" ").toLowerCase().includes(q);const matchesStatus=appliedStatus==="all"||b.booking_status===appliedStatus||b.payment_status===appliedStatus;const bookingDates=(b.booking_slots||[]).map(slot=>slot.booking_date);const matchesFrom=!appliedFromDate||bookingDates.some(date=>date>=appliedFromDate);const matchesTo=!appliedToDate||bookingDates.some(date=>date<=appliedToDate);const matchesDate=(!appliedFromDate&&!appliedToDate)||bookingDates.some(date=>(!appliedFromDate||date>=appliedFromDate)&&(!appliedToDate||date<=appliedToDate));return matches&&matchesStatus&&matchesFrom&&matchesTo&&matchesDate;}),[data.bookings,appliedQuery,appliedStatus,appliedFromDate,appliedToDate]);
 const pending=data.bookings.filter(b=>b.payment_status==="pending_verification").length; const verified=data.bookings.filter(b=>b.payment_status==="verified").length; const confirmed=data.bookings.filter(b=>b.booking_status==="confirmed").length; const refundOpen=data.refunds.filter(r=>["requested","approved"].includes(r.status)).length; const paidRevenue=data.bookings.filter(b=>b.payment_status==="paid"&&b.booking_status!=="cancelled").reduce((s,b)=>s+Number(b.total_amount||0),0); const refunded=data.refunds.filter(r=>r.status==="completed").reduce((s,r)=>s+Number(r.amount||0),0);
 return <main className="container">
  <section className="hero"><div className="logoBox">BUELO</div><div><span className="pill">OPERATIONS</span><h1>Reservations Control Center</h1><p>Verify payments, confirm bookings, reschedule court slots, process refunds, and review the audit trail.</p></div></section>
  <section className="card"><div className="grid grid-2"><div><label>Admin password</label><input type="password" value={code} onChange={e=>setCode(e.target.value)} /></div><div style={{display:"flex",alignItems:"end"}}><button className="btn btn-primary" disabled={!code||loading} onClick={load}>{loading?"Loading...":"Open Operations"}</button></div></div>{msg&&<p className={msg.includes("completed")?"success":"error"}>{msg}</p>}</section>
  {data.bookings.length>0&&<>
   <div className="grid metric-grid">
    <section className="card"><div className="muted">Pending Verification</div><div className="price">{pending}</div></section><section className="card"><div className="muted">Payment Verified</div><div className="price">{verified}</div></section><section className="card"><div className="muted">Confirmed</div><div className="price">{confirmed}</div></section><section className="card"><div className="muted">Open Refunds</div><div className="price">{refundOpen}</div></section><section className="card"><div className="muted">Paid Revenue</div><div className="price">{money(paidRevenue)}</div></section><section className="card"><div className="muted">Refunded</div><div className="price">{money(refunded)}</div></section>
   </div>
   <section className="card" style={{marginTop:16}}>
    <div className="operations-filter-grid">
      <div className="operations-search"><label>Search booking, customer, phone or email</label><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")runSearch();}} placeholder="Type a name, booking #, phone or email..."/></div>
      <div><label>Status filter</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All</option><option value="pending">Pending booking</option><option value="pending_verification">Payment to verify</option><option value="verified">Payment verified</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option><option value="refunded">Refunded</option></select></div>
      <div><label>From booking date</label><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></div>
      <div><label>To booking date</label><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></div>
      <div className="row operations-filter-actions"><button className="btn btn-secondary" onClick={applyNextSevenDays}>Next 7 Days</button><button className="btn btn-primary" onClick={runSearch}>Apply Filters</button><button className="btn btn-secondary" onClick={clearSearch}>Clear</button></div>
    </div>
    {(appliedQuery||appliedStatus!=="all"||appliedFromDate||appliedToDate)&&<div className="row" style={{marginTop:12}}><span className="muted">Active filters:</span>{appliedQuery&&<span className="pill">Search: {appliedQuery}</span>}{appliedStatus!=="all"&&<span className="pill">Status: {appliedStatus.replaceAll("_"," ")}</span>}{appliedFromDate&&<span className="pill">From: {appliedFromDate}</span>}{appliedToDate&&<span className="pill">To: {appliedToDate}</span>}<strong>{visible.length} match(es)</strong></div>}
   </section>
   <section className="card" style={{marginTop:16}}><div className="row space"><div><span className="pill">REVIEW QUEUE</span><h2 style={{marginBottom:4}}>Reservations</h2><div className="muted">Compact review cards for faster daily operations.</div></div><span className="pill">{visible.length} RESULT(S)</span></div><div className="grid" style={{marginTop:16}}>
    {visible.map(b=>{const refund=data.refunds.find(r=>r.booking_id===b.id);const events=data.events.filter(e=>e.booking_id===b.id).slice(0,8);const paymentDone=["verified","paid"].includes(b.payment_status);const bookingDone=b.booking_status==="confirmed";return <article key={b.id} style={{border:"1px solid #315f9f",borderRadius:18,background:"linear-gradient(180deg,#0b2243,#07182f)",overflow:"hidden",boxShadow:"0 12px 28px rgba(0,0,0,.18)"}}>
      <div style={{padding:18,borderBottom:"1px solid #244d87"}}>
        <div className="row space" style={{alignItems:"flex-start"}}><div style={{minWidth:0}}><div className="muted" style={{fontSize:12,fontWeight:700,letterSpacing:.5}}>BOOKING REFERENCE</div><strong style={{display:"block",fontSize:18,marginTop:3}}>{b.booking_code}</strong><div style={{fontSize:17,fontWeight:800,marginTop:10}}>{b.customer_name}</div><div className="muted" style={{marginTop:3,wordBreak:"break-word"}}>{b.customer_mobile}{b.customer_email?` · ${b.customer_email}`:""}</div></div><div style={{textAlign:"right",minWidth:120}}><div style={{fontSize:24,fontWeight:900}}>{money(b.total_amount)}</div><div className="muted">{b.total_hours} hour(s)</div></div></div>
        <div className="row" style={{marginTop:14}}><StatusBadge label="Booking" value={b.booking_status}/><StatusBadge label="Payment" value={b.payment_status}/>{refund&&<StatusBadge label="Refund" value={refund.status}/>}</div>
      </div>

      <div style={{padding:18,borderBottom:"1px solid #244d87"}}>
        <div className="row space"><div><div className="muted" style={{fontSize:12,fontWeight:700,letterSpacing:.5}}>SCHEDULE</div><h3 style={{margin:"4px 0 0"}}>Court reservations</h3></div><div className="muted">{(b.booking_slots||[]).length} slot(s)</div></div>
        <div className="grid" style={{marginTop:12}}>{(b.booking_slots||[]).map(s=><div key={s.id} style={{display:"flex",gap:12,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",padding:"12px 14px",border:"1px solid #315f9f",borderRadius:14,background:"#0a1d39"}}><div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><strong>📅 {s.booking_date}</strong><span className="muted">🏟 {s.courts?.name||"Court"}</span><span className="muted">🕐 {fmt(s.start_minute)} - {fmt(s.end_minute)}</span><StatusBadge label="Slot" value={s.status}/></div><button className="btn btn-secondary" onClick={async()=>{const date=prompt("New date (YYYY-MM-DD)",s.booking_date);if(!date)return;const courtName=prompt("New court: UNO Court or DOS Court",s.courts?.name||"");if(!courtName)return;const court=data.courts.find(c=>c.name.toLowerCase()===courtName.toLowerCase());if(!court){setMsg("Court not found.");return;}const time=prompt("New start hour in 24h format (example 19 for 7 PM)",String(Math.floor(s.start_minute/60)));if(time===null)return;const hour=Number(time);if(!Number.isInteger(hour)||hour<0||hour>23){setMsg("Invalid hour.");return;}await act("reschedule_slot",b.id,{slotId:s.id,bookingDate:date,courtId:court.id,startMinute:hour*60});}}>Reschedule</button></div>)}</div>
      </div>

      <div style={{padding:18,borderBottom:"1px solid #244d87"}}>
        <div className="grid grid-2">
          <div><div className="muted" style={{fontSize:12,fontWeight:700,letterSpacing:.5}}>PAYMENT</div><h3 style={{margin:"4px 0 12px"}}>Payment review</h3>{b.proof_url?<a className="btn btn-secondary" href={b.proof_url} target="_blank" rel="noreferrer">View Receipt</a>:<div className="muted">No payment proof uploaded.</div>}<div className="row" style={{marginTop:18}}>{paymentDone?<button className="btn" disabled style={{background:"#123d2b",color:"#bfffe0",border:"1px solid #2d8b61",cursor:"default"}}>✓ Payment Verified</button>:<button className="btn btn-primary" onClick={()=>act("verify_payment",b.id)}>Verify Payment</button>}<button className="btn btn-danger" disabled={paymentDone} onClick={()=>{const reason=prompt("Reason for rejecting payment?")||"Payment proof rejected";act("reject_payment",b.id,{reason})}}>Reject</button></div></div>
          <div><div className="muted" style={{fontSize:12,fontWeight:700,letterSpacing:.5}}>BOOKING</div><h3 style={{margin:"4px 0 12px"}}>Booking approval</h3><div className="row">{bookingDone?<button className="btn" disabled style={{background:"#123d2b",color:"#bfffe0",border:"1px solid #2d8b61",cursor:"default"}}>✓ Confirmed</button>:<button className="btn btn-primary" disabled={!paymentDone} onClick={()=>act("confirm_booking",b.id)}>Confirm Booking</button>}<button className="btn btn-danger" disabled={b.booking_status==="cancelled"} onClick={()=>{const reason=prompt("Cancellation reason?")||"Cancelled by admin";act("cancel_booking",b.id,{reason})}}>{b.booking_status==="cancelled"?"Cancelled":"Cancel Booking"}</button></div>{!paymentDone&&!bookingDone&&<div className="muted" style={{marginTop:10}}>Verify the payment first before confirming the reservation.</div>}</div>
        </div>
      </div>

      <div style={{padding:18}}>
        <div className="grid grid-2">
          <div><div className="muted" style={{fontSize:12,fontWeight:700,letterSpacing:.5}}>REFUND</div><h3 style={{margin:"4px 0 12px"}}>Refund management</h3>{!refund&&<button className="btn btn-secondary" onClick={()=>{const reason=prompt("Refund reason?")||"Customer refund request";act("request_refund",b.id,{amount:b.total_amount,reason})}}>Request Refund</button>}{refund?.status==='requested'&&<div className="row"><button className="btn btn-primary" onClick={()=>act("approve_refund",b.id)}>Approve Refund</button><button className="btn btn-danger" onClick={()=>act("reject_refund",b.id,{reason:prompt("Reason?")||"Refund rejected"})}>Reject</button></div>}{refund?.status==='approved'&&<button className="btn btn-primary" onClick={()=>act("complete_refund",b.id)}>Mark Refund Completed</button>}{refund&&<div className="muted" style={{marginTop:8}}>{money(refund.amount)} · {refund.reason}</div>}</div>
          <div><div className="muted" style={{fontSize:12,fontWeight:700,letterSpacing:.5}}>ADMIN NOTES</div><h3 style={{margin:"4px 0 12px"}}>Internal notes</h3><textarea defaultValue={b.admin_notes||""} id={`note-${b.id}`} style={{width:"100%",minHeight:86,background:"#081a34",color:"white",border:"1px solid #315f9f",borderRadius:12,padding:10}}/><button className="btn btn-secondary" style={{marginTop:8}} onClick={()=>{const el=document.getElementById(`note-${b.id}`) as HTMLTextAreaElement|null;act("save_note",b.id,{note:el?.value||""})}}>Save Note</button></div>
        </div>
        <details style={{marginTop:16,paddingTop:14,borderTop:"1px solid #244d87"}}><summary style={{cursor:"pointer",fontWeight:800}}>Audit Trail ({events.length})</summary><div style={{marginTop:10}}>{events.length===0?<div className="muted">No events yet.</div>:events.map(e=><div key={e.id} className="muted" style={{marginBottom:6}}>{new Date(e.created_at).toLocaleString()} · <strong>{e.event_type.replaceAll('_',' ')}</strong></div>)}</div></details>
      </div>
    </article>})}
   </div></section>
  </>}
 </main>;
}
